### ISSUE TITLE
panlex_swadesh shows "out of date" despite being updated

### ISSUE THREAD

**Issue by djokester** [nltk/nltk_data#65] opened 2017-03-02 07:39 UTC
Using the GUI to update panlex_swadesh. It is always displaying out of date despite repeatedly downloading the updates.

**Comment by gmarmstrong** [comment] 2017-03-28 21:00
I can confirm that this is an issue with at least nltk version 3.2.2. The status of `panlex_swadesh` is "out of date" despite attempts to download it from both the GUI and using `nltk.download(panlex_swadesh)`.

```
[>>> import nltk
[>>> nltk.download('panlex_swadesh')
[nltk_data] Downloading package panlex_swadesh to
[nltk_data]     /Users/guthriearmstrong/nltk_data...
True
```

The MD5 checksum `66dd080f09ac17db3d31bb4d667d0794` given for `panlex_swadesh.zip` in the file [nltk/nltk_data/blob/gh-pages/index.xml](https://github.com/nltk/nltk_data/blob/gh-pages/index.xml) does not match the checksum of my copy of `nltk_data/corpora/panlex_swadesh.zip`.

```
md5 panlex_swadesh.zip
MD5 (panlex_swadesh.zip) = 59a08f6c19d1d6d72cc03189983c8045
```

@djokester, is your checksum equal to mine?

**Comment by pavlin99th** [comment] 2017-03-30 11:37
If you visit https://dev.panlex.org/db/, you will notice that panlex_swadesh was updated.
The previous version is:
`panlex_swadesh-20150416.zip` with MD5 `59a08f6c19d1d6d72cc03189983c8045`

The newer one is:
`panlex_swadesh.zip` with MD5 `66dd080f09ac17db3d31bb4d667d0794`

MD5 sum was updated in https://github.com/nltk/nltk_data/blob/gh-pages/index.xml, but the archive file https://github.com/nltk/nltk_data/blob/gh-pages/packages/corpora/panlex_swadesh.zip was not.

One way to clear "out of date" message is to download the newer archive, place it in your `nltk_data/corpora` and unzip.

**Comment by stevenbird** [comment] 2017-04-13 10:36
Unfortunately the latest `panlex_swadesh.zip` is not a link to a dated version. This means we can't reference `panlex_swadesh.zip` (it will be updated and invalidate our checksum) and we can't reference `panlex_swadesh_20170103.zip` (because it doesn't exist).

```
2859562224 2699578 panlex_swadesh-20150416.zip
2317885344 2861668 panlex_swadesh.zip
```

@kamholz would you please:

```
mv panlex_swadesh.zip panlex_swadesh_20170103.zip
ln -s panlex_swadesh_20170103.zip panlex_swadesh.zip
```

**Comment by kamholz** [comment] 2017-04-17 22:26
>
> @kamholz <https://github.com/kamholz> would you please:
>
> mv panlex_swadesh.zip panlex_swadesh_20170103.zip
> ln -s panlex_swadesh_20170103.zip panlex_swadesh.zip
>
> Done. I'll CC Jonathan, so he can modify the code that generates the
Swadesh lists to create a dated file and maintain the symlink.

**Comment by stevenbird** [comment] 2017-05-10 03:39
Thanks @kamholz

**Comment by stevenbird** [comment] 2017-05-10 03:42
Resolved in https://github.com/nltk/nltk_data/commit/5ae9e2716262f2ba56db1e35b497846a18b2148c

**Closed as completed by stevenbird** 2017-05-10 03:42 UTC
