### ISSUE TITLE
Dear Jan Strunk: license of NLTK Data

### ISSUE THREAD

**Issue by hiDevman** [nltk/nltk_data#196] opened 2023-06-16 17:07 UTC
I read below link: 
https://github.com/nltk/nltk_data/issues/188
https://github.com/nltk/nltk/issues/3015

But No one answer about them.
Jan Strunk, Why don't you reply these questions?
Is it possible to use for commerical use?
Is it possible to redistributable?

**Comment by ekaf** [comment] 2024-10-03 14:07
duplicate of #188

**Closed as not planned** 2024-10-03 14:06 UTC
